### ISSUE TITLE
Some Questions about HyperCD

### ISSUE THREAD

**Issue by Golriz-code** [ark1234/ICCV2023-HyperCD#2]
Hello,
Thank you for your interesting paper.
I have some questions:
1.  Can you explain the rationale behind using Chamfer Distance (CD) and partial matching metrics for this task? What makes these metrics suitable for measuring dissimilarity in your problem?
2.  Could you provide some guidance on what determines the suitable numbers or resolution for the P1, P2, P3, and Pc point clouds in your specific application? Are there any considerations or best practices for choosing these resolutions, and how do they impact the quality of the predictions and the loss calculation?
3. Why is the loss value scaled by a factor of 1e3 (i.e., multiplied by 1000)? What is the motivation for this scaling?

**Comment by ark1234** [comment]
Thanks for asking. I am sorry for the late response; all the questions you asked were related with the baselines, snowflake, PoinTr, those setting are from their networks design, we proposed a loss function, so, for the fair comparison, we followed their setting and only change the CD part to HyperCD
