### ISSUE TITLE
Installation of hyptorch

### ISSUE THREAD

**Issue by WeijianZhang123** [ark1234/ICCV2023-HyperCD#4]
Hi, is there any instruction for installing hyptorch module?

**Comment by ark1234** [comment]
For HyperCD, no need for hyptorch, you just need to comment it, sorry for forgetting remove some irrelevant stuff

**Comment by WeijianZhang123** [comment]
> For HyperCD, no need for hyptorch, you just need to comment it, sorry for forgetting remove some irrelevant stuff

OK, it seems that geoopt is also unneccesary. Thanks for your quick reply!
